#!/usr/bin/env bash
# install and configure Nginx web server

# update the system and install Nginx
sudo apt update -y -qq && sudo apt-get -y install nginx
# start Nginx web server
sudo service nginx start
# make it listen on default port(80)
sudo ufw allow "Nginx HTTP"
# get the necessary grants to edit the served pages
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# create a backup file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# write "Hellow World!" into the served file
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
# restart Nginx after the changes made
sudo service nginx restart
