#!/ur/bin/env bash
# redirection using sed

# update the system and download nginx if it's not already downloaded
sudo apt update -y -qq && sudo apt-get install nginx -y
# start nginx
sudo service nginx start
# make it listen on default port(80)
sudo ufw allow "Nginx HTTP"
# get all permissions to edit config files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
# message to be served
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
# redirect ^/redirect_me to a youtube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# restart Nginx so the changes will be applied
sudo service nginx restart
