#!/usr/bin/env bash
# print "Best School" but print "bad luck" on the 4th pass and "good luck" on the 8th pass
x=0
while ((x < 10))
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
