#!/usr/bin/env bash
# displays numbers from 1 to 20 and print strings on 4, 9, and 17
x=1
while ((x <= 20))
do
	case $x in
		4)
			echo "$x"
			echo "bad luck from China"
			;;
		9)
			echo "$x"
			echo "bad luck from Japan"
			;;
		17)
			echo "$x"
			echo "bad luck from Italy"
			;;
		*)
			echo "$x"
			;;
	esac
	((x++))
done
